### ISSUE TITLE
not workking

### ISSUE THREAD

**Issue by dfgdrtgdrfg** [jbehrens94/PrivacyApp#2]
![error](https://cloud.githubusercontent.com/assets/10977094/9474650/9885ef96-4b6a-11e5-9e8b-b9b79aac97d6.png)

**Comment by jbehrens94** [comment]
I am not able to help and identify your error and I can't reproduce your steps.
Therefore I am going to close this issue.

**Comment by dfgdrtgdrfg** [comment]
I  just  run  it  normal with  version  Xcode  6  and   don’t even  start  the  simulator  for  iphone.


Savu Andreea
savuandreea1@gmail.com
